language: node_js
node_js:
  - "v5.7.0"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install
  - npm install -g codeclimate-test-reporter
script:
  - npm run test
  - codeclimate-test-reporter < coverage/report-lcov/lcov.info

addons:
    code_climate:
        repo_token: be79fc33b9210fb74bcbf2a355b309f0156f0d89393f5775575d59f345abf0d8
